spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8080
rsa:
  private-key: classpath:certificates/private.pem
  public-key: classpath:certificates/public.pem